### ISSUE TITLE
Compile time dependencies.

### ISSUE THREAD

**Issue by AliDehbansiahkarbon** [hindermath/TMySimpleChatGPTFMX#1]
You use **TMS FNC Cloud Pack**, but most developers don't have that pack.
Maybe it's better if you use **TRestClient** or any other open-source library.

**Comment by hindermath** [comment]
There you, @AliDehbansiahkarbon, are right. In the README.md I have now learned why I am currently using the FNC components and that I will see in the future if I can provide an alternative version without FNC components. Thanks for pointing out TRestClient, I'll have a look at that.
